base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  port: 3306
  pool: 5
  username: updates
  password: 

development:
  database: updates_dev
  <<: *base

staging:
  database: updates_staging
  <<: *base

test:
  database: updates_test
  <<: *base

production:
  database: updates_prod
  <<: *base


